services:
  db:
    image: postgres:15-alpine
    container_name: store_db_container
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - store-net

  app:
    build: .
    container_name: store_app_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - store-net

volumes:
  postgres_data:

networks:
  store-net:
    driver: bridge