spring.application.name=demo
server.port=8080
spring.datasource.url=jdbc:postgresql://db:5432/store_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver